config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get '/auth/:provider/callback' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/facebook.rb
module Facebook
  include HTTParty
  base_uri 'https://graph.facebook.com'

  def self.get_location(user)
    fields = 'location'
    query = {query: {fields: fields, access_token: user.facebook_token}}
    self.get("/me", query)
  end

  def self.get_posts(user)
    fields = 'place,from,message,link'
    query = {query: 
      {fields: fields, access_token: user.facebook_token, limit: 350}
    }
    self.get("/me/posts", query)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, length: {minimum: 1}, presence: true
  validates :facebook_id, numericality: true, presence: true

  class << self
    def from_omniauth(auth_hash)
      user = find_or_create_by(facebook_id: auth_hash['uid'])
      user.name = auth_hash['info']['name']
      user.facebook_token = auth_hash['credentials']['token']
      expires_at_timestamp = auth_hash['credentials']['expires_at']
      user.facebook_token_expires_at = Time.at(expires_at_timestamp).to_datetime
      user.save!
      user
    end
  end

  def update_location
    location_data = Facebook.get_location(self)
    location = location_data['location']['name']
    geodata = Geokit::Geocoders::MultiGeocoder.geocode(location)
    return geodata.lat, geodata.lng
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper

  def index
    user = current_user
    if user
      @latitude, @longitude = user.update_location
      posts = Facebook.get_posts(user)
      post_data = posts['data']
      @posts_with_location = filter_posts_with_location(post_data)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # TODO: better error messages
  def create
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
      login(@user)
      flash[:success] = "Welcome, #{@user.name}!"
    rescue
      flash[:warning] = "There was an error while trying to authenticate your 
        Facebook credentials"
    end
    redirect_to root_path
  end

  def destroy
    if current_user
      logout
      flash[:success] = "Logout successful"
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def filter_posts_with_location(post_data)
    post_data.reduce({data: []}) do |posts, post|
      if post['place']
        location = post['place']['location']
        coords = [location['latitude'], location['longitude']]
        location_name = post['place']['name']
        location_city = post['place']['location']['city']
        author = post['from']['name']
        message = post['message'] || ""
        post_hash = {
          coords: coords, 
          location_name: location_name, 
          location_city: location_city, 
          author: author, 
          message: message
        }
        posts[:data] << post_hash
      end
      posts
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session[:user_id] = nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostMapper</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- facebook open graph -->
  <meta property="og:url"                content="http://www.post-mapper.herokuapp.com" />
  <meta property="og:type"               content="website" />
  <meta property="og:title"              content="PostMapper" />
  <meta property="og:description"        content="View geolocations of posts for you and your friends" />
  <!-- TODO -->
  <!-- <meta property="og:image"              content="" /> -->
</head>

<body>
   <!-- facebook sdk -->
   <div id="fb-root"></div>
   <script>(function(d, s, id) {
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) return;
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7&appId=616729855165047";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));</script>

  <nav class="navbar navbar-inverse">
    <div class="container">
      <div id="navbar">
        <%= link_to 'PostMapper', root_path, class: 'navbar-brand' %>
        
        <% if current_user %>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav">
            <li><%= link_to 'Facebook Login', '/auth/facebook' %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>

    <div class="row">

      <%= yield %>

    </div>
  </div>

  <footer class="footer">
    <div class="container">
      <!-- facebook like and share buttons -->
      <div class="fb-like" data-href="http://post-mapper.herokuapp.com" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
    </div>
  </footer>
</body>
</html>

app/views/posts/index.html.erb
<div class="jumbotron">
<% if current_user %>

  <!-- google maps -->
  <div id="map"></div>
  <script>
    function initMap() {
      // center on user location
      var userLocation = {lat: <%= @latitude %>, lng: <%= @longitude %>}

      var map = new google.maps.Map(document.getElementById('map'), {
        center: userLocation,
        zoom: 10
      });

      // posts filtered to those with location data
      var posts = <%= raw @posts_with_location.to_json %>['data'];

      // make markers on map for each post
      posts.forEach(function(post) {
        var infoContent = '<div id="info-window">' +
          [post.author, post.message, post.location_name, post.location_city].join('<br>') +
          '</div>';
        var infoWindow = new google.maps.InfoWindow({content: infoContent});

        var lat = post.coords[0],
            lng = post.coords[1];
        var marker = new google.maps.Marker({
          position: {lat: lat, lng: lng},
          map: map
        });

        // mouseover / mouseout
        marker.addListener('mouseover', function() {
          infoWindow.open(map, marker);
        });
        marker.addListener('mouseout', function() {
          infoWindow.close();
        });
      });
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_api_key'] %>&callback=initMap"></script>

<% else %>
    <h1>Welcome!</h1>
    <p>Sign in through Facebook to get started.</p>
    <%= link_to 'Facebook Login', '/auth/facebook' %>
<% end %>
</div>